### ISSUE TITLE
build broken: Task 'installApp' not found in root project 'bin'.

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-fopub#48]
```
:!asciidoctor -b docbook -d book -a data-uri! 'Bitcoin-The_New_Age_Of_Crime_E
conomy.adoc' && fopub  'Bitcoin-The_New_Age_Of_Crime_Economy.xml'  && evince
'Bitcoin-The_New_Age_Of_Crime_Economy.pdf'
asciidoctor: WARNING: Bitcoin-The_New_Age_Of_Crime_Economy.adoc: line 48: inv
alid style for open block: note
Initializing application...

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installApp' not found in root project 'bin'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace opt
ion to get the stack trace. Run with --info or --debug option to get more log
 output.
Failed to initialize application

shell returned 1
```

**Comment by mojavelinux** [comment]
I just tested it and it works fine for me. I'd need to know more about your environment in order to help you debug. For instance:

1. What OS are you using?
2. Which version of Java is on your path?
3. What is the output when you turn on `--stacktrace` (you need to edit the fopub file to add this flag where gradle is called)
4. Why are you not using Asciidoctor PDF?

**Comment by getreu** [comment]
I have not paid attention to that the directories: `asciidoctor-fopub/.gradle` and `asciidoctor-fopub/build` have to be writeable for users. Now it works.

**Comment by getreu** [comment]
Another problem was that I executed a symbolic link `fopub` in `/usr/local/bin`. It seems that gradle does not find it's files this way.

Now I execute `\usr\local\...\fopub` with absolute path and it works.
